# This file was generated by GoReleaser. DO NOT EDIT.
cask "autobahn" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "bb1eedc0cedea61a9866dd7058cc01db389a1d82f81645b465c657b2f176215f"
      url "https://github.com/danielriddell21/autobahn/releases/download/v#{version}/autobahn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c9e3fbfd796dd966886ce9ccdb7aee8cf7bb7180607ebf72a4d18961cfc57b0"
      url "https://github.com/danielriddell21/autobahn/releases/download/v#{version}/autobahn_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "autobahn"
  desc "A 3D driving game with a camera-only autopilot"
  homepage "https://github.com/danielriddell21/autobahn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autobahn"

  # No zap stanza required

  caveats <<~EOS
    autobahn opens a raylib window and is macOS-only; on Linux/Windows, build from source with -tags x11.
  EOS
end
