# Generated by letsgo-cask. Do not edit; the next release will overwrite it.
cask "autobahn" do
  version "1.0.1"

  on_arm do
    url "https://github.com/danielriddell21/autobahn/releases/download/v1.0.1/autobahn_1.0.1_darwin_arm64.tar.gz"
    sha256 "540368bd0c952eb78c8e4d1f3f3e8487b3772b395a663b0b6d649449ef317e6e"
  end

  on_intel do
    url "https://github.com/danielriddell21/autobahn/releases/download/v1.0.1/autobahn_1.0.1_darwin_amd64.tar.gz"
    sha256 "39400da8055e6581e4ec941245e98d17e8e3aa618f20d05ddd442b81abaee3b0"
  end

  name "autobahn"
  desc "A 3D driving game with a camera-only autopilot"
  homepage "https://github.com/danielriddell21/autobahn"
  license "MIT"

  binary "autobahn"

  caveats <<~EOS
    autobahn opens a raylib window and is macOS-only; on Linux/Windows, build from source with -tags x11.
  EOS
end
