# This file was generated by GoReleaser. DO NOT EDIT.
cask "autobahn" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "200043e0495312309a7362b5f7a08abeb64eb1db50cbba1af08ec958b0264e7a"
      url "https://github.com/danielriddell21/autobahn/releases/download/v#{version}/autobahn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7aaa56cea36cd28f886e978cbf6ee449b53803ca1613fb6c93c8c802bfc722ef"
      url "https://github.com/danielriddell21/autobahn/releases/download/v#{version}/autobahn_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "autobahn"
  desc "A 3D driving game with a camera-only autopilot"
  homepage "https://github.com/danielriddell21/autobahn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autobahn"

  # No zap stanza required

  caveats <<~EOS
    autobahn opens a raylib window and is macOS-only; on Linux/Windows, build from source with -tags x11.
  EOS
end
