# This file was generated by GoReleaser. DO NOT EDIT.
cask "galapagos" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "78e7ebaa6d90beb753d9f7869ac49e1c952b98879f23080be8153f53fa7c63e4"
      url "https://github.com/danielriddell21/galapagos/releases/download/v#{version}/galapagos-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "464625e54d62d7e5a7fd64197055ba4bced4f788375397ed89a0579575d5505c"
      url "https://github.com/danielriddell21/galapagos/releases/download/v#{version}/galapagos-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "galapagos"
  desc "Visualize learning algorithms in real time (native macOS window + browser demo)"
  homepage "https://github.com/danielriddell21/galapagos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "galapagos"

  # No zap stanza required

  caveats <<~EOS
    The native window uses Metal and is macOS-only; it also runs every CLI
    command and `galapagos serve` for the browser demo. On Linux or Windows,
    install the formula instead and run `galapagos serve`.
  EOS
end
