# This file was generated by GoReleaser. DO NOT EDIT.
cask "galapagos" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "3fd65eadbe066ca65115e9a444bf541e3d39472df82863998a56092103eb9332"
      url "https://github.com/danielriddell21/galapagos/releases/download/v#{version}/galapagos-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8499e6fd9257db0b747a79dc21600ca33082af7d1741082063ad28384dfedf25"
      url "https://github.com/danielriddell21/galapagos/releases/download/v#{version}/galapagos-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "galapagos"
  desc "Visualize learning algorithms in real time (native macOS window + browser demo)"
  homepage "https://github.com/danielriddell21/galapagos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "galapagos"

  # No zap stanza required

  caveats <<~EOS
    The native window uses Metal and is macOS-only; it also runs every CLI
    command and `galapagos serve` for the browser demo. On Linux or Windows,
    install the formula instead and run `galapagos serve`.
  EOS
end
