# Generated by letsgo-cask. Do not edit; the next release will overwrite it.
cask "galapagos" do
  version "0.6.1"

  on_arm do
    url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.1/galapagos-gui_0.6.1_darwin_arm64.tar.gz"
    sha256 "caa7f93ed6782e663230514c125471b52e93fbe8dd89d9c1a8d1594a91d63379"
  end

  on_intel do
    url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.1/galapagos-gui_0.6.1_darwin_amd64.tar.gz"
    sha256 "c114854153947edcc3ca0a39913bb5297319125117482d07f63b2739f22b4822"
  end

  name "galapagos"
  desc "Visualize learning algorithms in a native macOS window"
  homepage "https://github.com/danielriddell21/galapagos"
  license "MIT"

  binary "galapagos"

  caveats <<~EOS
    The native window uses Metal and is macOS-only; it also runs every CLI command. On Linux or Windows, install the formula instead.
  EOS
end
