# This file was generated by GoReleaser. DO NOT EDIT.
cask "gambit" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "dda930b343a0c00fa68be33461e9756225ab263c1f4fe291b9e49568a044c6d2"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd21cbeda77895a0a6d260736be5eb08ec37110362be869c260d47dca66b3fb4"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gambit"
  desc "Watch two chess agents play in a native macOS window"
  homepage "https://github.com/danielriddell21/gambit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gambit"

  # No zap stanza required

  caveats <<~EOS
    The gambit board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
