# This file was generated by GoReleaser. DO NOT EDIT.
cask "gambit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "458e5a1bc7d81f7d5d60e42eee4e9415b8f109867e142d918c426dc1d5133e08"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d827b3ad3fc35c81ceed64363667e952ec4ea5509b58a84373d331d2b2627911"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gambit"
  desc "Watch two chess agents play in a native macOS window"
  homepage "https://github.com/danielriddell21/gambit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gambit"

  # No zap stanza required

  caveats <<~EOS
    The gambit board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
