# This file was generated by GoReleaser. DO NOT EDIT.
cask "gambit" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5fc1eb0fa4240ed9ef1a278b95e590a2f4c2d8b43497da663c34f7f5e8470ff7"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a85df2e5bb84551db18a34370750feabd40dc565008bba64b8004ecd0f10e019"
      url "https://github.com/danielriddell21/gambit/releases/download/v#{version}/gambit-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "gambit"
  desc "Watch two chess agents play in a native macOS window"
  homepage "https://github.com/danielriddell21/gambit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gambit"

  # No zap stanza required

  caveats <<~EOS
    The gambit board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
