# This file was generated by GoReleaser. DO NOT EDIT.
cask "hegemony" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3e166ac960d76ee3a5d9ce7472e3c23940de4c926db8abf508a9f7b6817ca6c9"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97f3a0deb9364e3621939056413804a84b812578584cd5e7a7f8c3bee1b009c8"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "hegemony"
  desc "A territory-war simulation where competing algorithms fight to control a shared grid."
  homepage "https://github.com/danielriddell21/hegemony"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hegemony"

  # No zap stanza required

  caveats <<~EOS
    The hegemony board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
