# This file was generated by GoReleaser. DO NOT EDIT.
cask "hegemony" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "04efb4a3ac9e2b9f827137bc672755dfddd4fa693b554636a02bb867a4116986"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c74af79c3dc802bd59a134c17b869164d83c16b7b023d003feb94f505e2af0d8"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "hegemony"
  desc "A territory-war simulation where competing algorithms fight to control a shared grid."
  homepage "https://github.com/danielriddell21/hegemony"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hegemony"

  # No zap stanza required

  caveats <<~EOS
    The hegemony board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
