# This file was generated by GoReleaser. DO NOT EDIT.
cask "hegemony" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "c462411ddc2b279cefc7424bbd01ba0f34df8517c29338e8149caa95c2897932"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a136c625bd6d0d58457c0e982c2d39f66084b97a8851198d40c57178932c3589"
      url "https://github.com/danielriddell21/hegemony/releases/download/v#{version}/hegemony-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "hegemony"
  desc "A territory-war simulation where competing algorithms fight to control a shared grid."
  homepage "https://github.com/danielriddell21/hegemony"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hegemony"

  # No zap stanza required

  caveats <<~EOS
    The hegemony board opens an Ebiten window and is macOS-only; on Linux/Windows install the formula and run in the terminal.
  EOS
end
