# This file was generated by GoReleaser. DO NOT EDIT.
cask "nemesis" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "334627846013ce57bcb5d0773aae9e69655dca229c86c77bcd4efe00446e9205"
      url "https://github.com/danielriddell21/nemesis/releases/download/v#{version}/nemesis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f770b4512d780f65c2871249074d1383dd5fcca8589c3bb35609e2ae181d580d"
      url "https://github.com/danielriddell21/nemesis/releases/download/v#{version}/nemesis_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nemesis"
  desc "A procedurally generated first-person stealth game hunted by an Alien-Isolation-style AI"
  homepage "https://github.com/danielriddell21/nemesis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nemesis"

  # No zap stanza required

  caveats <<~EOS
    nemesis opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
