# Generated by letsgo-cask. Do not edit; the next release will overwrite it.
cask "nemesis" do
  version "0.5.1"

  on_arm do
    url "https://github.com/danielriddell21/nemesis/releases/download/v0.5.1/nemesis_0.5.1_darwin_arm64.tar.gz"
    sha256 "c9cd9865f14db073dc3722bb937bec6d262c2d5e231661ea6c66f6eb8b73075c"
  end

  on_intel do
    url "https://github.com/danielriddell21/nemesis/releases/download/v0.5.1/nemesis_0.5.1_darwin_amd64.tar.gz"
    sha256 "8c480e07c259baafadab4b0a61c07d688e5d26cc99d44960af8bbc457bce2914"
  end

  name "nemesis"
  desc "A procedurally generated first-person stealth game hunted by an Alien-Isolation-style AI"
  homepage "https://github.com/danielriddell21/nemesis"
  license "MIT"

  binary "nemesis"

  caveats <<~EOS
    nemesis opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
