# This file was generated by GoReleaser. DO NOT EDIT.
cask "nemesis" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bbc2ebc14d0bf9a5693becad2f995c7bcc48492614575c8233076fc55837fdb1"
      url "https://github.com/danielriddell21/nemesis/releases/download/v#{version}/nemesis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f6001d0ec786de150a25a603fa14edb18091a933fedf123f468ba840367ff96"
      url "https://github.com/danielriddell21/nemesis/releases/download/v#{version}/nemesis_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nemesis"
  desc "A procedurally generated first-person stealth game hunted by an Alien-Isolation-style AI"
  homepage "https://github.com/danielriddell21/nemesis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nemesis"

  # No zap stanza required

  caveats <<~EOS
    nemesis opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
