# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandemonium" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9ea7835c1ac0d4694fc38b0e72b6990b4084d701b49c6e9449c16ff6f41ebdfa"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "33861fecb2bde250b388ba302dfaaa841bcb5a6008413d44c3c670b37926b98b"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "pandemonium"
  desc "A procedurally generated DOOM-style raycaster FPS"
  homepage "https://github.com/danielriddell21/pandemonium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandemonium"

  # No zap stanza required

  caveats <<~EOS
    pandemonium opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
