# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandemonium" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "83d62d6be4c5cc34a17508de0f181a4d916566db79df3fb24fe14c45e5286996"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8874ea549b439d2d7db595c9cc8fcab5b8d910c0f77999f50f210e3c860dbe38"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "pandemonium"
  desc "A procedurally generated DOOM-style raycaster FPS"
  homepage "https://github.com/danielriddell21/pandemonium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandemonium"

  # No zap stanza required

  caveats <<~EOS
    pandemonium opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
