# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandemonium" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "40298db23a07ce4136bbe087f007142e46f983b033793f204346fee7c4d112a5"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e3d309748d1ad9b49364f61b63d4364a10e9c1d1e0b8eb42425869e6f6649ce"
      url "https://github.com/danielriddell21/pandemonium/releases/download/v#{version}/pandemonium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "pandemonium"
  desc "A procedurally generated DOOM-style raycaster FPS"
  homepage "https://github.com/danielriddell21/pandemonium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandemonium"

  # No zap stanza required

  caveats <<~EOS
    pandemonium opens an Ebiten window and is macOS-only; on Linux/Windows, build from source.
  EOS
end
