# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubix" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "8b17dad40ddff6865c45abb6ec009f2af7377c4cc25b4b5f7758689d5c3328b4"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0453f6e4293c582f0a311311951f2abedfeeddf81278653fdd5584e874771e59"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rubix"
  desc "A Rubik's cube solver with a native macOS 3D visualizer"
  homepage "https://github.com/danielriddell21/rubix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubix"

  # No zap stanza required

  caveats <<~EOS
    The rubix visualizer opens a window and is macOS-only.
  EOS
end
