# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubix" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "61dbc645481ef494c2e23ad772b2db985b2d828ac71a319f2c2f4e810366db82"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "39cb1c645d8c57802b91fdb87217a75b06ff68feac451b74f2e27cba3b64d4b0"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "rubix"
  desc "A Rubik's cube solver with a native macOS 3D visualizer"
  homepage "https://github.com/danielriddell21/rubix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubix"

  # No zap stanza required

  caveats <<~EOS
    The rubix visualizer opens a window and is macOS-only.
  EOS
end
