# This file was generated by GoReleaser. DO NOT EDIT.
cask "rubix" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "9dbd89792e7287087a4eb9e37bb450d2f9bdb9c7f7f61d361fefd8f7c168ab88"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "315d486916a9f7645fb22bddc7c5583360a280e098b10761271cdfd137507cb9"
      url "https://github.com/danielriddell21/rubix/releases/download/v#{version}/rubix-gui_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "rubix"
  desc "A Rubik's cube solver with a native macOS 3D visualizer"
  homepage "https://github.com/danielriddell21/rubix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rubix"

  # No zap stanza required

  caveats <<~EOS
    The rubix visualizer opens a window and is macOS-only.
  EOS
end
