# This file was generated by GoReleaser. DO NOT EDIT.
cask "vivarium" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "4a888a4c792871c44752d6a3b431ca94bad956ef16cbb6cbedc33bb7dfee93e6"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c9ffdda5d2265e3c328ce3976f88a508c77ceee80e3722527782f6e9069d2f8"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vivarium"
  desc "Watch an evolving 2D ecosystem in a native macOS window"
  homepage "https://github.com/danielriddell21/vivarium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vivarium"

  # No zap stanza required

  caveats <<~EOS
    The vivarium window is macOS-only; the same binary also runs 'vivarium headless' for batch simulations.
  EOS
end
