# This file was generated by GoReleaser. DO NOT EDIT.
cask "vivarium" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d56375fd4087153cda3392470bb2c0bd4cf54c59eb75f184c7d7760bb11bea70"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "87d4109c62b47f3af2de74716b49fdecb4f61d15be9ca201bc98fbc1ba3d7b28"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vivarium"
  desc "Watch an evolving 2D ecosystem in a native macOS window"
  homepage "https://github.com/danielriddell21/vivarium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vivarium"

  # No zap stanza required

  caveats <<~EOS
    The vivarium window is macOS-only; the same binary also runs 'vivarium headless' for batch simulations.
  EOS
end
