# This file was generated by GoReleaser. DO NOT EDIT.
cask "vivarium" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "bc1bfe35ea7df726ad8db23e6fc1a0b95c4a506b77b6c93cfc3dec02a8780ecc"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "696645a783b80afe6781a6600569512fa92e11da5044703e84be72ccc9555b7c"
      url "https://github.com/danielriddell21/vivarium/releases/download/v#{version}/vivarium_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "vivarium"
  desc "Watch an evolving 2D ecosystem in a native macOS window"
  homepage "https://github.com/danielriddell21/vivarium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vivarium"

  # No zap stanza required

  caveats <<~EOS
    The vivarium window is macOS-only; the same binary also runs 'vivarium headless' for batch simulations.
  EOS
end
