# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FactorioMcp < Formula
  desc "A Claude Code plugin that lets Claude play Factorio 2.0"
  homepage "https://github.com/danielriddell21/factorio-mcp"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.2/factorio-mcp_0.0.2_darwin_amd64.tar.gz"
      sha256 "addb94fb087044c27943f886eb44be03a85cc8650d330a3c2e5dde77704ff426"

      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.2/factorio-mcp_0.0.2_darwin_arm64.tar.gz"
      sha256 "ad01d0d31199c9e3059ceafca2fb359657ae775c76e10144684549aaf0d2452b"

      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.2/factorio-mcp_0.0.2_linux_amd64.tar.gz"
      sha256 "cac11d59f538830b2dcd088c0ae99cfaf8f4e8fa67139fe2cad4fd8e1bb35e77"
      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.2/factorio-mcp_0.0.2_linux_arm64.tar.gz"
      sha256 "a3c5562666416099fbabd1119913ab480ab8ab0079113a5497267d1f1965d6e4"
      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
  end

  test do
    system "#{bin}/factorio-mcp", "--version"
  end
end
