# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FactorioMcp < Formula
  desc "A Claude Code plugin that lets Claude play Factorio 2.0"
  homepage "https://github.com/danielriddell21/factorio-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.1/factorio-mcp_0.0.1_darwin_amd64.tar.gz"
      sha256 "66b58aa138e1b2b535314cdb49526b995e8a52e249c781d00687e20c017f3f03"

      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.1/factorio-mcp_0.0.1_darwin_arm64.tar.gz"
      sha256 "0f3ce4a1b3769f5862049f3ed5dc48cd5197d295440c3d1ad0c175fc239d862c"

      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.1/factorio-mcp_0.0.1_linux_amd64.tar.gz"
      sha256 "f20d073d971fddc678a15a33db039ec5c376389f6f201418c0ec34859a5b8847"
      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.1/factorio-mcp_0.0.1_linux_arm64.tar.gz"
      sha256 "db5b451495b6a9328c17ee7c7b2b301460c9949edfc44249183710fb2125bcc3"
      define_method(:install) do
        bin.install "factorio-mcp"
      end
    end
  end
end
