# Generated by letsgo. Do not edit; the next release will overwrite it.
class FactorioMcp < Formula
  desc "just a factorio bot"
  homepage "https://github.com/danielriddell21/factorio-mcp"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.3/factorio-mcp_0.0.3_darwin_amd64.tar.gz"
      sha256 "ae1bae86c1f40f1e1a44beba046dcd4f70147829320f460bf94a94d635ff83ea"
    end
    on_arm do
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.3/factorio-mcp_0.0.3_darwin_arm64.tar.gz"
      sha256 "2136cb09fab1711df9be70fa3cfe83e91df18d71257c62f7adb47baca51de77d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.3/factorio-mcp_0.0.3_linux_amd64.tar.gz"
      sha256 "f6b39ee5fa85d353dcaffbe3ebb3392f9239c499f6f76063ccdb9389efaca112"
    end
    on_arm do
      url "https://github.com/danielriddell21/factorio-mcp/releases/download/v0.0.3/factorio-mcp_0.0.3_linux_arm64.tar.gz"
      sha256 "d06fd789c4b037d804ae84f95e6bc6b0dd31871849666ebc8b5eb42e66615c28"
    end
  end

  def install
    bin.install "factorio-mcp"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.0.3", shell_output("#{bin}/factorio-mcp --version")
  end
end
