# Generated by letsgo. Do not edit; the next release will overwrite it.
class Fiatlux < Formula
  desc "just an agent in a void"
  homepage "https://github.com/danielriddell21/fiat-lux"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.7/fiatlux_0.1.7_darwin_amd64.tar.gz"
      sha256 "6db972897e13b1cf9809c8a39100389912e3059ec79ccf7c5ad6d6667774fc63"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.7/fiatlux_0.1.7_darwin_arm64.tar.gz"
      sha256 "316f3c20a53ec1f9e3193353b535b4e264dffeef719959e4bf84e25d421bcade"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.7/fiatlux_0.1.7_linux_amd64.tar.gz"
      sha256 "a2028227db1db1f2a86aafc4d7a0280611be619c5bbc56ec47b6fc3260de714d"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.7/fiatlux_0.1.7_linux_arm64.tar.gz"
      sha256 "6fdb7552e061676e1967be4da972a21ca0eba69c90bbb69cbbe2aef5efe7f282"
    end
  end

  def install
    bin.install "fiatlux"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.1.7", shell_output("#{bin}/fiatlux --version")
  end
end
