# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fiatlux < Formula
  desc "Let there be light."
  homepage "https://github.com/danielriddell21/fiat-lux"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.2/fiatlux_0.1.2_macos_x86_64.tar.gz"
      sha256 "58bafdd15b40e3a862ca7d1f74e81bd2d790a033170a95f1b7fde3db9bb462d0"

      define_method(:install) do
        bin.install "fiatlux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.2/fiatlux_0.1.2_macos_arm64.tar.gz"
      sha256 "eba4b02502c31e401a85c5c32ec9b29e3129dc037497ce0495ab8ef0cc1c5be1"

      define_method(:install) do
        bin.install "fiatlux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.2/fiatlux_0.1.2_linux_x86_64.tar.gz"
      sha256 "66f4adb7edf81fda1930f0a101e8514b1b4e3ef3a389e70a0b326d00c48e904b"
      define_method(:install) do
        bin.install "fiatlux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.2/fiatlux_0.1.2_linux_arm64.tar.gz"
      sha256 "261dd71298d7887889c6a5aef7c149a67fcd8f879a7d04cc947c32b69c326c5a"
      define_method(:install) do
        bin.install "fiatlux"
      end
    end
  end

  test do
    system "#{bin}/fiatlux", "--version"
  end
end
