# Generated by letsgo. Do not edit; the next release will overwrite it.
class FiatluxATNext < Formula
  desc "just an agent in a void"
  homepage "https://github.com/danielriddell21/fiat-lux"
  version "0.1.9-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.9-rc.1/fiatlux_0.1.9-rc.1_darwin_amd64.tar.gz"
      sha256 "7436b88dbe8b5f66c2ae5ade96156ee11729917beb57fcdbc8980ddc4058c70c"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.9-rc.1/fiatlux_0.1.9-rc.1_darwin_arm64.tar.gz"
      sha256 "2707b55f6a540e7828a936b5f010d73dd4a7dd1a8cc4cdcf8bbfb040eb2f116b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.9-rc.1/fiatlux_0.1.9-rc.1_linux_amd64.tar.gz"
      sha256 "876710b184fb3600a9cbefd92b87431c3ea75425171c74177e0f5bcde2d7ca96"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.9-rc.1/fiatlux_0.1.9-rc.1_linux_arm64.tar.gz"
      sha256 "ff64703c7897e92ce3e45578de31bc746ae511ac4c280a50b03c9ca4255e9c76"
    end
  end

  def install
    bin.install "fiatlux"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.1.9-rc.1", shell_output("#{bin}/fiatlux --version")
  end
end
