# Generated by letsgo. Do not edit; the next release will overwrite it.
class FiatluxATNext < Formula
  desc "just an agent in a void"
  homepage "https://github.com/danielriddell21/fiat-lux"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.8/fiatlux_0.1.8_darwin_amd64.tar.gz"
      sha256 "3515a706c7ea5961b6f87850df1f05da2c5e46e7be69ecee014631e92b280f01"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.8/fiatlux_0.1.8_darwin_arm64.tar.gz"
      sha256 "1639231cb40c8331b848b567b208f81349fbbfd20f3ea996165bed145792f540"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.8/fiatlux_0.1.8_linux_amd64.tar.gz"
      sha256 "617c21443bda04f449fe637d9cfca73436a64ff965b841132930c1bb08c3b4cd"
    end
    on_arm do
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.8/fiatlux_0.1.8_linux_arm64.tar.gz"
      sha256 "342ef4c0ee55c642ec5f840076be9a4e1eea1000b4b4314dbee83ac09a18816a"
    end
  end

  def install
    bin.install "fiatlux"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.1.8", shell_output("#{bin}/fiatlux --version")
  end
end
