# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fiatlux < Formula
  desc "Let there be light."
  homepage "https://github.com/danielriddell21/fiat-lux"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.5/fiatlux_0.1.5_darwin_amd64.tar.gz"
      sha256 "a89534634036599db05958a442af9262ebf04fda3664f2acbe95514ee0c2a998"

      define_method(:install) do
        bin.install "fiatlux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.5/fiatlux_0.1.5_darwin_arm64.tar.gz"
      sha256 "164548eee1f6d024cd1da3f95c0105eebecbb4574b4b665e0a1f354302456da9"

      define_method(:install) do
        bin.install "fiatlux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.5/fiatlux_0.1.5_linux_amd64.tar.gz"
      sha256 "1074f9d23e741e5df0123455139614c58937c4111fef7dc7c42d9d4ae7d7df1b"
      define_method(:install) do
        bin.install "fiatlux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/fiat-lux/releases/download/v0.1.5/fiatlux_0.1.5_linux_arm64.tar.gz"
      sha256 "3c96b62a84ae324ad6e0df49223d135fefdc21a5414c7b032172a079074d1127"
      define_method(:install) do
        bin.install "fiatlux"
      end
    end
  end

  test do
    system "#{bin}/fiatlux", "--version"
  end
end
