# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Galapagos < Formula
  desc "Visualize learning algorithms in real time"
  homepage "https://github.com/danielriddell21/galapagos"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.0.1/galapagos_0.0.1_darwin_amd64.tar.gz"
      sha256 "769cbefdeaff35c8bd6362d3c71888bc586ce705902a8d6201a0f66f184994cf"

      define_method(:install) do
        bin.install "galapagos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.0.1/galapagos_0.0.1_darwin_arm64.tar.gz"
      sha256 "38313205d6f80c8dcdab72488479d6bf0e57854a9895d82937f550c728dd49c2"

      define_method(:install) do
        bin.install "galapagos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.0.1/galapagos_0.0.1_linux_amd64.tar.gz"
      sha256 "8c259466b90970cf351c38bd97947c3f96b6145383240426557ace0cb480fac8"
      define_method(:install) do
        bin.install "galapagos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.0.1/galapagos_0.0.1_linux_arm64.tar.gz"
      sha256 "30b6250ec960effe167d7b6369839d1c50659319a26d6e6bea76511fc8e51977"
      define_method(:install) do
        bin.install "galapagos"
      end
    end
  end

  test do
    system "#{bin}/galapagos", "--version"
  end
end
