# Generated by letsgo. Do not edit; the next release will overwrite it.
class GalapagosATNext < Formula
  desc "just a learning visualiser"
  homepage "https://github.com/danielriddell21/galapagos"
  version "0.6.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.2/galapagos_0.6.2_darwin_amd64.tar.gz"
      sha256 "3e3ef83173114991f1ef1e9d69241eb4780e1fb7b137bc3f26f6e84ace4b3435"
    end
    on_arm do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.2/galapagos_0.6.2_darwin_arm64.tar.gz"
      sha256 "1b06a21be4aa631232c9fff5e0cf2cc35099563f6a2e7a2118ecefbb8cb18152"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.2/galapagos_0.6.2_linux_amd64.tar.gz"
      sha256 "553847eeee9b34e1d56e8030128a4e633d8a774d39b413897d777319d8731b61"
    end
    on_arm do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.2/galapagos_0.6.2_linux_arm64.tar.gz"
      sha256 "dc602d60df0757b845b998f79f23b6a7b02e04f7aff3eb9c00a26fb55c3a23a3"
    end
  end

  def install
    bin.install "galapagos"
  end

  def caveats
    <<~EOS
      `galapagos serve` compiles the browser demo on demand, so it needs Go and a checkout of the repository.
    EOS
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.6.2", shell_output("#{bin}/galapagos --version")
  end
end
