# Generated by letsgo. Do not edit; the next release will overwrite it.
class GalapagosATNext < Formula
  desc "just a learning visualiser"
  homepage "https://github.com/danielriddell21/galapagos"
  version "0.6.3-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.3-rc.1/galapagos_0.6.3-rc.1_darwin_amd64.tar.gz"
      sha256 "6b494532fa72de05332915966e2842f4d4597d0fb82fcda6a9c8144c46e40085"
    end
    on_arm do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.3-rc.1/galapagos_0.6.3-rc.1_darwin_arm64.tar.gz"
      sha256 "878bd37fe3a1e82012487341249643b3e391df83cf7d49330fa764477ac762ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.3-rc.1/galapagos_0.6.3-rc.1_linux_amd64.tar.gz"
      sha256 "6198cb2bf3fc2735056db300b06bfde2e6bc70e64f19d2daa4cef595a40623d8"
    end
    on_arm do
      url "https://github.com/danielriddell21/galapagos/releases/download/v0.6.3-rc.1/galapagos_0.6.3-rc.1_linux_arm64.tar.gz"
      sha256 "815a9abc1ffe454cd98b74fdec4d0d488ef06ebd92faa836cfbaa4ab3a327b49"
    end
  end

  def install
    bin.install "galapagos"
  end

  def caveats
    <<~EOS
      `galapagos serve` compiles the browser demo on demand, so it needs Go and a checkout of the repository.
    EOS
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.6.3-rc.1", shell_output("#{bin}/galapagos --version")
  end
end
