# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gambit < Formula
  desc "Two chess agents play each other, logged in algebraic notation"
  homepage "https://github.com/danielriddell21/gambit"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.0.1/gambit_0.0.1_darwin_amd64.tar.gz"
      sha256 "1f02d9513a615eea13d1a889b681e3aab30c6c4d2a4cc12d068bb33b622ec575"

      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.0.1/gambit_0.0.1_darwin_arm64.tar.gz"
      sha256 "3fff68657ccd9090fdbcfa5d7912447df5ad1fb43d303645a27fee3c0379e9e5"

      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.0.1/gambit_0.0.1_linux_amd64.tar.gz"
      sha256 "5f271c336abba8f180bd97f08cfc5f21c9aa970c2019cc8d12cd4b5f1fcda5ee"
      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.0.1/gambit_0.0.1_linux_arm64.tar.gz"
      sha256 "e6c35d198427ab90ec736671c0995715b75483056732463ca44ca87f6cfa1d85"
      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  test do
    system "#{bin}/gambit", "--version"
  end
end
