# Generated by letsgo. Do not edit; the next release will overwrite it.
class GambitATNext < Formula
  desc "just a chess engine"
  homepage "https://pkg.go.dev/github.com/danielriddell21/gambit"
  version "0.6.2-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/gambit/releases/download/v0.6.2-rc.1/gambit_0.6.2-rc.1_darwin_amd64.tar.gz"
      sha256 "bed855a97080ae8136c68fc5a3cd19e411ceb98e1784b2403e2184cd5d2f6dc9"
    end
    on_arm do
      url "https://github.com/danielriddell21/gambit/releases/download/v0.6.2-rc.1/gambit_0.6.2-rc.1_darwin_arm64.tar.gz"
      sha256 "7afd61f597e1d6e8a59be5abe2bcf6c3d6ef4a54b7352d3bdd6797b2709521e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/gambit/releases/download/v0.6.2-rc.1/gambit_0.6.2-rc.1_linux_amd64.tar.gz"
      sha256 "6956a49abc6eaad942c59a2629919b617c5a37b8ca36ef7e416187467baca0ac"
    end
    on_arm do
      url "https://github.com/danielriddell21/gambit/releases/download/v0.6.2-rc.1/gambit_0.6.2-rc.1_linux_arm64.tar.gz"
      sha256 "d2aa4137d2ffba20938dbfdb19657fd8f3dcf2bc0a584228c6014b3a2cadd774"
    end
  end

  def install
    bin.install "gambit"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.6.2-rc.1", shell_output("#{bin}/gambit --version")
  end
end
