# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gambit < Formula
  desc "Two chess agents play each other, logged in algebraic notation"
  homepage "https://github.com/danielriddell21/gambit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.3.0/gambit_0.3.0_darwin_amd64.tar.gz"
      sha256 "0aa74ee6b3e28492faa75d8b9594d983a11136ef38b021297b7687a9eea563d5"

      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.3.0/gambit_0.3.0_darwin_arm64.tar.gz"
      sha256 "aaac0bfde0eac7a7ca826e679a3e18ad942f65f06aa1153a81c2a9b7428ed49f"

      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.3.0/gambit_0.3.0_linux_amd64.tar.gz"
      sha256 "5c182ced15efa56a510daa8959c4ac2084b82481cce4f9050088986cfe34741e"
      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.3.0/gambit_0.3.0_linux_arm64.tar.gz"
      sha256 "6d69ede50bc4a51ebd211d461e50bfd3c1eb44fc245826c61bd668c9b780f912"
      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  test do
    system "#{bin}/gambit", "--version"
  end
end
