# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gambit < Formula
  desc "Two chess agents play each other, logged in algebraic notation"
  homepage "https://github.com/danielriddell21/gambit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.1.0/gambit_0.1.0_darwin_amd64.tar.gz"
      sha256 "ce7472b4118b762101a0f4ca47d9e349d9b9250b5a4d94f1ba87866e9e741283"

      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.1.0/gambit_0.1.0_darwin_arm64.tar.gz"
      sha256 "b67b6317b7ea6785c781232cbdc9f25301889d6f17f4c939844f842dc4db4cc8"

      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.1.0/gambit_0.1.0_linux_amd64.tar.gz"
      sha256 "5540ce0aad1baf636c4d5cbebd454659970b16a152ea7d2050d12577c8472ebf"
      define_method(:install) do
        bin.install "gambit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/gambit/releases/download/v0.1.0/gambit_0.1.0_linux_arm64.tar.gz"
      sha256 "65d4dcb4fc3506d1eebd8e9a4d7c39dbc73ea1329a384c8245b791cf15d77e35"
      define_method(:install) do
        bin.install "gambit"
      end
    end
  end

  test do
    system "#{bin}/gambit", "--version"
  end
end
