# Generated by letsgo. Do not edit; the next release will overwrite it.
class HegemonyATNext < Formula
  desc "just a territory war"
  homepage "https://github.com/danielriddell21/hegemony"
  version "0.7.2-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.2-rc.1/hegemony_0.7.2-rc.1_darwin_amd64.tar.gz"
      sha256 "e1d5c7973449a8c1e08b457bbc3fade49921ae9041f6c1525582504c8f684550"
    end
    on_arm do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.2-rc.1/hegemony_0.7.2-rc.1_darwin_arm64.tar.gz"
      sha256 "9c3ea5d6f8bc6157d4a4c2ba14ca654ebd7f06f1bfda5a1c2a6eea8c86cea7fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.2-rc.1/hegemony_0.7.2-rc.1_linux_amd64.tar.gz"
      sha256 "0807b2af35556e2242d97556b7bced42717dfabe7472f7e3e82bb0712cbbd4bb"
    end
    on_arm do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.2-rc.1/hegemony_0.7.2-rc.1_linux_arm64.tar.gz"
      sha256 "c553009eff83616c9eb99725b0d9cc857cd8d15c76a14bc02a2c2c252e8c3fc9"
    end
  end

  def install
    bin.install "hegemony"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.7.2-rc.1", shell_output("#{bin}/hegemony --version")
  end
end
