# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hegemony < Formula
  desc "A territory-war simulation where competing algorithms fight to control a shared grid."
  homepage "https://github.com/danielriddell21/hegemony"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.2.0/hegemony_0.2.0_darwin_amd64.tar.gz"
      sha256 "0a93d0bfc7f90cbf5a5833715603c3de4365497c43fa9ace4fe59945887b4665"

      define_method(:install) do
        bin.install "hegemony"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.2.0/hegemony_0.2.0_darwin_arm64.tar.gz"
      sha256 "c825a19c1cf4736df5f3d6ea5b75fb1e10edf7798c757158d8dcf8311a16d549"

      define_method(:install) do
        bin.install "hegemony"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.2.0/hegemony_0.2.0_linux_amd64.tar.gz"
      sha256 "410a371cd9967e00e07c0580247dd6d1c5fed0c310903ebd651e117f41bb8986"
      define_method(:install) do
        bin.install "hegemony"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.2.0/hegemony_0.2.0_linux_arm64.tar.gz"
      sha256 "27bc17a1818411c7a1d40982e72a09666f3e8473f43fbac07ab97b5508cb17c1"
      define_method(:install) do
        bin.install "hegemony"
      end
    end
  end

  test do
    system "#{bin}/hegemony", "--version"
  end
end
