# Generated by letsgo. Do not edit; the next release will overwrite it.
class Hegemony < Formula
  desc "just a territory war"
  homepage "https://github.com/danielriddell21/hegemony"
  version "0.7.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.1/hegemony_0.7.1_darwin_amd64.tar.gz"
      sha256 "f1ea404c781a22d088e2cada8067099334dd07d20eca6d5e094b585adcc9d0f8"
    end
    on_arm do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.1/hegemony_0.7.1_darwin_arm64.tar.gz"
      sha256 "dab1d503c4df25a380e7f2cda6d6d83b23388feb637db6ea511671f1fb5715e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.1/hegemony_0.7.1_linux_amd64.tar.gz"
      sha256 "818438b5c185045e337a9fd9079a402a6e13d698e9753dc07be68834eed7d12b"
    end
    on_arm do
      url "https://github.com/danielriddell21/hegemony/releases/download/v0.7.1/hegemony_0.7.1_linux_arm64.tar.gz"
      sha256 "8e2aed5d0d3a8538b8cd8c5577bbbd29b14524c2191823c65e1c3f029997b470"
    end
  end

  def install
    bin.install "hegemony"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.7.1", shell_output("#{bin}/hegemony --version")
  end
end
