# Generated by letsgo. Do not edit; the next release will overwrite it.
class Letsgo < Formula
  desc "just a release tool"
  homepage "https://github.com/danielriddell21/letsgo"
  version "0.25.0"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.25.0/letsgo_0.25.0_darwin_amd64.tar.gz"
      sha256 "1d38499104c0152e704fffcf72de59b2ef91a601d1aac354d3f35101462f861e"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.25.0/letsgo_0.25.0_darwin_arm64.tar.gz"
      sha256 "234d0398f0dbe9cc074abe597fd151d57a0a05cce6f984bfe482ab52c5d47eab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.25.0/letsgo_0.25.0_linux_amd64.tar.gz"
      sha256 "ff5857d070c067ca1115404434510fcd69f9383b310beadbeed7a1e2430f5bc0"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.25.0/letsgo_0.25.0_linux_arm64.tar.gz"
      sha256 "d0d55e9d54c349cbea2b376401165730ffbd3a6833a1c667dd9075a552785160"
    end
  end

  def install
    bin.install "letsgo"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.25.0", shell_output("#{bin}/letsgo --version")
  end
end
