# Generated by letsgo. Do not edit; the next release will overwrite it.
class Letsgo < Formula
  desc "just a release tool"
  homepage "https://github.com/danielriddell21/letsgo"
  version "0.31.0"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.31.0/letsgo_0.31.0_darwin_amd64.tar.gz"
      sha256 "e88b613175e2c223190a19bc25286067479b804d5e6421485683736954553994"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.31.0/letsgo_0.31.0_darwin_arm64.tar.gz"
      sha256 "66af9be6103ea3f4fc8a7a1ca1f09c8af2fa7c2b42ac34b9b953648d517b1b06"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.31.0/letsgo_0.31.0_linux_amd64.tar.gz"
      sha256 "c16df7bf73b1829cbc075182622346275776e29c4177749036cb7bca2c607dea"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.31.0/letsgo_0.31.0_linux_arm64.tar.gz"
      sha256 "0fb9f72913b65a6c44c50e1da61d8e711f352a05ae02fbf7a16a58f6ed0a2cf7"
    end
  end

  def install
    bin.install "letsgo"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.31.0", shell_output("#{bin}/letsgo --version")
  end
end
