# Generated by letsgo. Do not edit; the next release will overwrite it.
class LetsgoATNext < Formula
  desc "just a release tool"
  homepage "https://github.com/danielriddell21/letsgo"
  version "0.35.0-rc.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.35.0-rc.4/letsgo_0.35.0-rc.4_darwin_amd64.tar.gz"
      sha256 "e5c3c0ca8b228edd405622a18d3b71a8921974f55dae366779c12ea6b368ea53"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.35.0-rc.4/letsgo_0.35.0-rc.4_darwin_arm64.tar.gz"
      sha256 "7ffb73a292d455dd6f81aecab2a2a0f3e170d57a1e61307947a1aa9abddb9a46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.35.0-rc.4/letsgo_0.35.0-rc.4_linux_amd64.tar.gz"
      sha256 "f4b754670d4421ba16d71c4460ba7045cbbdbc2ae30170bd2f32cc2a622ce854"
    end
    on_arm do
      url "https://github.com/danielriddell21/letsgo/releases/download/v0.35.0-rc.4/letsgo_0.35.0-rc.4_linux_arm64.tar.gz"
      sha256 "2a7c17c935a3fb372eea4c2f9207df7bda633518f433e0305a11b5dd8b088449"
    end
  end

  def install
    bin.install "letsgo"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.35.0-rc.4", shell_output("#{bin}/letsgo --version")
  end
end
