# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Merkelbrot < Formula
  desc "Zoomable, fractal-style visualiser for Merkle DAGs and trees"
  homepage "https://github.com/danielriddell21/merkelbrot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.1.0/merkelbrot_0.1.0_darwin_amd64.tar.gz"
      sha256 "1d2ffb5991df8eb21719eaf02d2ef560da10b69fde6c2ce0432a77dde744fb68"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.1.0/merkelbrot_0.1.0_darwin_arm64.tar.gz"
      sha256 "6ad0ef36a4413d49772087467201c3f636b8ad887c49c40dbe0081e6575e76cf"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.1.0/merkelbrot_0.1.0_linux_amd64.tar.gz"
      sha256 "f4209007313d868eec8ec1af55845aa9e1025e6b6db119d42798c591160d64f9"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.1.0/merkelbrot_0.1.0_linux_arm64.tar.gz"
      sha256 "92d58f9356d08be5e34dce89a906c230dbb1f502e3fa404ef1d5378835ca24d7"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  test do
    system "#{bin}/merkelbrot", "--version"
  end
end
