# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Merkelbrot < Formula
  desc "Zoomable, fractal-style visualiser for Merkle DAGs and trees"
  homepage "https://github.com/danielriddell21/merkelbrot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.2.0/merkelbrot_0.2.0_darwin_amd64.tar.gz"
      sha256 "30a3e7ea4f17d1cf24d5d3af4e36a3ab05fe94694d027f8aaa6452636df15588"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.2.0/merkelbrot_0.2.0_darwin_arm64.tar.gz"
      sha256 "c8fe6545792e70153b3b2813f0c68232e61fde6d03dac7dcacae6da51e7b2e4b"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.2.0/merkelbrot_0.2.0_linux_amd64.tar.gz"
      sha256 "944f10e561b8677cd5a62290f1e931f11bb3ab078f58cc61e03ab6c6be334cf2"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.2.0/merkelbrot_0.2.0_linux_arm64.tar.gz"
      sha256 "c87c4088a46c43e84198f5fa2a735eb6a0fc25059168e222f5b02319e87ba967"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  test do
    system "#{bin}/merkelbrot", "--version"
  end
end
