# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Merkelbrot < Formula
  desc "Zoomable, fractal-style visualiser for Merkle DAGs and trees"
  homepage "https://github.com/danielriddell21/merkelbrot"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.0.1/merkelbrot_0.0.1_darwin_amd64.tar.gz"
      sha256 "ef68b58f3c5bf19dc386c03fdf6b1716f185ec169adb6bc7837566911e86204c"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.0.1/merkelbrot_0.0.1_darwin_arm64.tar.gz"
      sha256 "1ef1a29c2d8586e67909ce2331785c2e86899cbb1c0fe2ca56382f150860e886"

      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.0.1/merkelbrot_0.0.1_linux_amd64.tar.gz"
      sha256 "c333cfba2dcba9cf28d6af18c7c526ee776e42fddc979ddfccbaa496e288bce4"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/merkelbrot/releases/download/v0.0.1/merkelbrot_0.0.1_linux_arm64.tar.gz"
      sha256 "947406767e1ffbafd8109c8e1ff097a4e202265893205e582b06674149fa2f7e"
      define_method(:install) do
        bin.install "merkelbrot"
      end
    end
  end

  test do
    system "#{bin}/merkelbrot", "version"
  end
end
