# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Narrata < Formula
  desc "An embedded, local-first narration runtime for Go"
  homepage "https://github.com/danielriddell21/narrata"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.0/narrata_0.1.0_darwin_amd64.tar.gz"
      sha256 "32f591301a86019ea198a0acbb777b02c423a99fd280233ad28607c2a36977fc"

      define_method(:install) do
        bin.install "narrata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.0/narrata_0.1.0_darwin_arm64.tar.gz"
      sha256 "6ca30d860647b2ae963553e7b85598de2fc90ad355d0daf9b8bf7e342a34526c"

      define_method(:install) do
        bin.install "narrata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.0/narrata_0.1.0_linux_amd64.tar.gz"
      sha256 "815928abae4edd2c823fc57a076c0d7e8265505f17f317184483ab91083be356"
      define_method(:install) do
        bin.install "narrata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.0/narrata_0.1.0_linux_arm64.tar.gz"
      sha256 "f8f8225d87f119004a741723e5cf54361bd084fc537736655dac8271e18690ee"
      define_method(:install) do
        bin.install "narrata"
      end
    end
  end

  test do
    system "#{bin}/narrata", "--version"
  end
end
