# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Narrata < Formula
  desc "An embedded, local-first narration runtime for Go"
  homepage "https://github.com/danielriddell21/narrata"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.1/narrata_0.1.1_darwin_amd64.tar.gz"
      sha256 "fa9be9aecc9952afef093a63314ec2c3754c477cdf2b9d74e1468cf15eb85bd6"

      define_method(:install) do
        bin.install "narrata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.1/narrata_0.1.1_darwin_arm64.tar.gz"
      sha256 "51192edb2d3f12428a5041dc291ff52461a3f1303d3bd4fcd48d62bba7ffa486"

      define_method(:install) do
        bin.install "narrata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.1/narrata_0.1.1_linux_amd64.tar.gz"
      sha256 "b9ba37d83ccda974b811cd341de965349c48d0bab930273e746f88b11a269b76"
      define_method(:install) do
        bin.install "narrata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/narrata/releases/download/v0.1.1/narrata_0.1.1_linux_arm64.tar.gz"
      sha256 "45dfc393fb5e2905c79dc3ae15d4a80b84ac25433d8304c85375fcdfa90bfd5f"
      define_method(:install) do
        bin.install "narrata"
      end
    end
  end

  test do
    system "#{bin}/narrata", "--version"
  end
end
