# Generated by letsgo. Do not edit; the next release will overwrite it.
class RubixATNext < Formula
  desc "just a cube solver"
  homepage "https://pkg.go.dev/github.com/danielriddell21/rubix"
  version "0.4.3-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.3-rc.1/rubix_0.4.3-rc.1_darwin_amd64.tar.gz"
      sha256 "9b1d27fdf16eea0e1164119a94a8c7e3c6ebfd2a17b6deeb58173933848c07f3"
    end
    on_arm do
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.3-rc.1/rubix_0.4.3-rc.1_darwin_arm64.tar.gz"
      sha256 "cd89d82ea603b242c8d64486268dec7d8dfcdf75759529d1e043ed01aa18e1cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.3-rc.1/rubix_0.4.3-rc.1_linux_amd64.tar.gz"
      sha256 "790a21dd475299ed6df7e24c2d421d44f87daefd2ef1940ec50412511d3254c2"
    end
    on_arm do
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.3-rc.1/rubix_0.4.3-rc.1_linux_arm64.tar.gz"
      sha256 "271deaf354780488a5dc9d97b67027de32a2e66243e5f794f48e5e689bdc5741"
    end
  end

  def install
    bin.install "rubix"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.4.3-rc.1", shell_output("#{bin}/rubix --version")
  end
end
