# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rubix < Formula
  desc "A Rubik's cube solver with nine strategies and a 3D visualizer"
  homepage "https://github.com/danielriddell21/rubix"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.0/rubix_0.4.0_darwin_amd64.tar.gz"
      sha256 "2c7c89dd91018c3248b4e4867ff1d4bdfc7f70a9a9a8cc6e59cc58dd4d38d175"

      define_method(:install) do
        bin.install "rubix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.0/rubix_0.4.0_darwin_arm64.tar.gz"
      sha256 "16a84f3dfd6b9a7a89b729ad1dd9c55709cc2dc7c3f2b74065f712054b6644e2"

      define_method(:install) do
        bin.install "rubix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.0/rubix_0.4.0_linux_amd64.tar.gz"
      sha256 "3b52d1cf85f648ddf0ab53b2e13260fe7e1d9cadc282cde0fa3baa5abfdd6c28"
      define_method(:install) do
        bin.install "rubix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.4.0/rubix_0.4.0_linux_arm64.tar.gz"
      sha256 "2ee6b4917a6d1885386578525625ad5fceec6720b0a58818792b8c60c098b3d2"
      define_method(:install) do
        bin.install "rubix"
      end
    end
  end

  test do
    system "#{bin}/rubix", "--version"
  end
end
