# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rubix < Formula
  desc "A Rubik's cube solver with nine strategies and a 3D visualizer"
  homepage "https://github.com/danielriddell21/rubix"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.0.1/rubix_0.0.1_darwin_amd64.tar.gz"
      sha256 "30eb54a2274563b5970bd1ea24af1c19c74dd01d29cc915b58a37fac9d3fd7e0"

      define_method(:install) do
        bin.install "rubix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.0.1/rubix_0.0.1_darwin_arm64.tar.gz"
      sha256 "ab5d6df36fe1af6553ba521593220c499bd8f4a08b032e828edc103611fbb33d"

      define_method(:install) do
        bin.install "rubix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.0.1/rubix_0.0.1_linux_amd64.tar.gz"
      sha256 "088fb75ab7523ba317a2317cf2b791a7abfb24ea8c7bc007e154ff4b0266871b"
      define_method(:install) do
        bin.install "rubix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/rubix/releases/download/v0.0.1/rubix_0.0.1_linux_arm64.tar.gz"
      sha256 "96eb262754e4aae2b8373fff022e676a34a0d308a83321367ca432f020e87c4c"
      define_method(:install) do
        bin.install "rubix"
      end
    end
  end

  test do
    system "#{bin}/rubix", "--version"
  end
end
