# Generated by letsgo. Do not edit; the next release will overwrite it.
class Toolshed < Formula
  desc "just a shed of terminal toys"
  homepage "https://github.com/danielriddell21/toolshed"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.5/toolshed_0.0.5_darwin_amd64.tar.gz"
      sha256 "2ca7f4a7f8f5828eff9762c11a4c7491d8fce97d29e878079a2e41e906ec1162"
    end
    on_arm do
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.5/toolshed_0.0.5_darwin_arm64.tar.gz"
      sha256 "6939b259da056a3c9386906367ab3fd7592413e2ee8fc27ec97ce4712cad8a93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.5/toolshed_0.0.5_linux_amd64.tar.gz"
      sha256 "87802f8dfce98bcd49d63e71e44d101821f4a17384cf5a07775ebf5773010389"
    end
    on_arm do
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.5/toolshed_0.0.5_linux_arm64.tar.gz"
      sha256 "8b55a280e2266728d44196da9ebd9dd2f041d7b97b5bf6d89e2db54713933ed1"
    end
  end

  def install
    bin.install "crabs", "duck", "fish", "fractal", "garden", "life", "markov", "maze", "sandbox", "snail", "turing"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.0.5", shell_output("#{bin}/crabs --version")
  end
end
