# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolshed < Formula
  desc "A small, serious-looking collection of command-line tools"
  homepage "https://github.com/danielriddell21/toolshed"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.1/toolshed_0.0.1_darwin_amd64.tar.gz"
      sha256 "5a6e0908dc1a6de2c68f1b616d729dd1330ba0f9c6fa6ef0478fa9084684ad8d"

      define_method(:install) do
        bin.install "crabs", "duck", "fish", "garden", "snail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.1/toolshed_0.0.1_darwin_arm64.tar.gz"
      sha256 "7c9aa4c8479b4898d13ab8a2398a94bf61a4c7b90ca60b7afa49ce2f9ffcc93e"

      define_method(:install) do
        bin.install "crabs", "duck", "fish", "garden", "snail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.1/toolshed_0.0.1_linux_amd64.tar.gz"
      sha256 "19dbb0242201f04e80f59d3ec6294013c48d642493cdd2575f5fa45df6206ce6"
      define_method(:install) do
        bin.install "crabs", "duck", "fish", "garden", "snail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.1/toolshed_0.0.1_linux_arm64.tar.gz"
      sha256 "5af3cfad57e74efe8ea820fb3124710b358c88e98e412e925273c0788a5b03a9"
      define_method(:install) do
        bin.install "crabs", "duck", "fish", "garden", "snail"
      end
    end
  end
end
