# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolshed < Formula
  desc "A small, serious-looking collection of command-line tools"
  homepage "https://github.com/danielriddell21/toolshed"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.2/toolshed_0.0.2_darwin_amd64.tar.gz"
      sha256 "a483a7b73ddf9b541368b0cf42aaf0b25e5fa17ce46843239190f3ee75ecdb49"

      define_method(:install) do
        bin.install "crabs", "duck", "fractal", "garden", "life", "markov", "maze", "sandbox", "snail", "turing"
        bin.install "fish" => "aquarium"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.2/toolshed_0.0.2_darwin_arm64.tar.gz"
      sha256 "367891547f149b463c27108a5fa2004e143f663fdf810c6a5b125fcf65a1274a"

      define_method(:install) do
        bin.install "crabs", "duck", "fractal", "garden", "life", "markov", "maze", "sandbox", "snail", "turing"
        bin.install "fish" => "aquarium"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.2/toolshed_0.0.2_linux_amd64.tar.gz"
      sha256 "0eb454cd1918fddce5751b319e1ab27005e25b04bc6a3cdc176949a26137be10"
      define_method(:install) do
        bin.install "crabs", "duck", "fractal", "garden", "life", "markov", "maze", "sandbox", "snail", "turing"
        bin.install "fish" => "aquarium"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/toolshed/releases/download/v0.0.2/toolshed_0.0.2_linux_arm64.tar.gz"
      sha256 "96bf6008d41ab696624aef96263a2cc921e3a087cd9f6216ec67b4fba6dc79e8"
      define_method(:install) do
        bin.install "crabs", "duck", "fractal", "garden", "life", "markov", "maze", "sandbox", "snail", "turing"
        bin.install "fish" => "aquarium"
      end
    end
  end
end
