# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unum < Formula
  desc "A unified developer tool suite — JSON analysis, type generation, and more"
  homepage "https://github.com/danielriddell21/unum"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/unum/releases/download/v0.8.0/unum_0.8.0_darwin_amd64.tar.gz"
      sha256 "f8179c4974199fa58cf3e325a0f078326908045004c9707282fbb784e4b8b297"

      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/unum/releases/download/v0.8.0/unum_0.8.0_darwin_arm64.tar.gz"
      sha256 "4c8ed9f5d118ff7dafac378c6f055d66f8f897a36189fd0b2748b8295df3c26a"

      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v0.8.0/unum_0.8.0_linux_amd64.tar.gz"
      sha256 "4176f90e0df0be7dd8d0a4e097e3275d2e407c68ecbbb7112f94cce6088a043d"
      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v0.8.0/unum_0.8.0_linux_arm64.tar.gz"
      sha256 "9448cbb3867cb0306fd241140e3acb4916dfe6d367847eeb8dac00b8fc0fc1ba"
      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  test do
    system "#{bin}/unum", "--version"
  end
end
