# Generated by letsgo. Do not edit; the next release will overwrite it.
class UnumATNext < Formula
  desc "just a dev tool"
  homepage "https://github.com/danielriddell21/unum"
  version "1.9.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.3/unum_1.9.3_darwin_amd64.tar.gz"
      sha256 "fb9071e113308217189a90246da919c1288920d84e79f706fae5666c1d9f7da9"
    end
    on_arm do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.3/unum_1.9.3_darwin_arm64.tar.gz"
      sha256 "1b85f9874e2d1069432fcd3cda29097a84f4e52da61e90fc84917c5e933312fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.3/unum_1.9.3_linux_amd64.tar.gz"
      sha256 "1fbec0317414e9a9468054c1eab0f974c596a7ae001c51fa0ad9bd1f4509824c"
    end
    on_arm do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.3/unum_1.9.3_linux_arm64.tar.gz"
      sha256 "a3483a67d5671019182628d9a0bfb10fcdf71f247097ab7f911f40430477b1e7"
    end
  end

  def install
    bin.install "unum"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "1.9.3", shell_output("#{bin}/unum --version")
  end
end
