# Generated by letsgo. Do not edit; the next release will overwrite it.
class UnumATNext < Formula
  desc "just a dev tool"
  homepage "https://github.com/danielriddell21/unum"
  version "1.9.5-rc.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.5-rc.1/unum_1.9.5-rc.1_darwin_amd64.tar.gz"
      sha256 "d6099903055a7988f7837c9141f42f6fd98d74631077bbad3efd766965e3fb32"
    end
    on_arm do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.5-rc.1/unum_1.9.5-rc.1_darwin_arm64.tar.gz"
      sha256 "7282ded4979506247206b1860ebc6c3a13ecb0291b5979744dc392351abf04de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.5-rc.1/unum_1.9.5-rc.1_linux_amd64.tar.gz"
      sha256 "f1a08e37464d208853e088ce8993b57723716d55940b67492e02fcda7c342081"
    end
    on_arm do
      url "https://github.com/danielriddell21/unum/releases/download/v1.9.5-rc.1/unum_1.9.5-rc.1_linux_arm64.tar.gz"
      sha256 "2718db2756311b72aa1263cc8b2e7a8e0138e74460c6ad3a12828b6f8f387488"
    end
  end

  def install
    bin.install "unum"
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "1.9.5-rc.1", shell_output("#{bin}/unum --version")
  end
end
