# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unum < Formula
  desc "A unified developer tool suite — JSON analysis, type generation, and more"
  homepage "https://github.com/danielriddell21/unum"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/unum/releases/download/v1.0.0/unum_1.0.0_darwin_amd64.tar.gz"
      sha256 "dd44f9dd2830387318ae74a55cf57e9874d9438105e8c40a041bdec15f7dca52"

      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/unum/releases/download/v1.0.0/unum_1.0.0_darwin_arm64.tar.gz"
      sha256 "30ad69c757e9d0ac9dae024ba590dfe1871ce22641420ddd7aa15d8e85478267"

      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v1.0.0/unum_1.0.0_linux_amd64.tar.gz"
      sha256 "7dcec2ee56ffe1f051baff131e18dfbed5ab3f3e9e2b8dfe5645cd9dc1ac1deb"
      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v1.0.0/unum_1.0.0_linux_arm64.tar.gz"
      sha256 "33ae7947841d0f45479d9db5ef1d94002cbc4351de6daa3b7cbf9dc8180c4783"
      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  test do
    system "#{bin}/unum", "--version"
  end
end
