# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unum < Formula
  desc "A unified developer tool suite — JSON analysis, type generation, and more"
  homepage "https://github.com/danielriddell21/unum"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danielriddell21/unum/releases/download/v0.7.1/unum_0.7.1_darwin_amd64.tar.gz"
      sha256 "6bcd443076aaabe09a4201f2fd84f55e1f22c8af39cb9c22ffc2e11a9a605386"

      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danielriddell21/unum/releases/download/v0.7.1/unum_0.7.1_darwin_arm64.tar.gz"
      sha256 "26fdcb9f1f53c0d901834cd784f2f9e97b4be6e49f8de3d99dc8fcaf9865a52c"

      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v0.7.1/unum_0.7.1_linux_amd64.tar.gz"
      sha256 "20c58983bb333f9ccd906c0a4b147434e1d2181a1eda95702c98d3cd5477d342"
      define_method(:install) do
        bin.install "unum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielriddell21/unum/releases/download/v0.7.1/unum_0.7.1_linux_arm64.tar.gz"
      sha256 "692681a2a9cecaa73608b707de6eeee7fe7d3bce33123f1be919589bc52205b4"
      define_method(:install) do
        bin.install "unum"
      end
    end
  end

  test do
    system "#{bin}/unum", "--version"
  end
end
