# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vivarium < Formula
  desc "Evolving 2D ecosystem simulation; use 'vivarium headless' for batch runs"
  homepage "https://github.com/danielriddell21/vivarium"
  version "0.2.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/danielriddell21/vivarium/releases/download/v0.2.0/vivarium_0.2.0_linux_amd64.tar.gz"
    sha256 "497741cd62c8bb6b856cd6b3e5c889487e45c638019a0ea075df91c4ebc5fe2f"
    define_method(:install) do
      bin.install "vivarium"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/danielriddell21/vivarium/releases/download/v0.2.0/vivarium_0.2.0_linux_arm64.tar.gz"
    sha256 "949ffdc88ae49aca6704e1d6d1f3ad9f899cd3fbffb6f7817bae5c604a8ae121"
    define_method(:install) do
      bin.install "vivarium"
    end
  end

  def caveats
    <<~EOS
      The native GUI is macOS-only: on macOS install the cask with 'brew install --cask vivarium'. Elsewhere use 'vivarium headless' for batch runs.
    EOS
  end
end
