# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vivarium < Formula
  desc "Evolving 2D ecosystem simulation; use 'vivarium headless' for batch runs"
  homepage "https://github.com/danielriddell21/vivarium"
  version "0.3.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/danielriddell21/vivarium/releases/download/v0.3.0/vivarium_0.3.0_linux_amd64.tar.gz"
    sha256 "9d32bed4c452e22605c1fbdadd489e6fdad0f4ab4428802ba0c9efd1a405e032"
    define_method(:install) do
      bin.install "vivarium"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/danielriddell21/vivarium/releases/download/v0.3.0/vivarium_0.3.0_linux_arm64.tar.gz"
    sha256 "77bb2c8cdf57fec59c085f18a6b5e1735dae27fb11d00e9450735ea8340824bb"
    define_method(:install) do
      bin.install "vivarium"
    end
  end

  def caveats
    <<~EOS
      The native GUI is macOS-only: on macOS install the cask with 'brew install --cask vivarium'. Elsewhere use 'vivarium headless' for batch runs.
    EOS
  end
end
