# Generated by letsgo. Do not edit; the next release will overwrite it.
class VivariumATNext < Formula
  desc "just an ecosystem"
  homepage "https://github.com/danielriddell21/vivarium"
  version "0.5.2-rc.1"
  license "MIT"

  on_linux do
    on_intel do
      url "https://github.com/danielriddell21/vivarium/releases/download/v0.5.2-rc.1/vivarium_0.5.2-rc.1_linux_amd64.tar.gz"
      sha256 "9dce2214ad18f4aca1cf4b420b061e5f8655dea1b6ec7d2e1dc28827bdc84861"
    end
    on_arm do
      url "https://github.com/danielriddell21/vivarium/releases/download/v0.5.2-rc.1/vivarium_0.5.2-rc.1_linux_arm64.tar.gz"
      sha256 "6084ffd17e8cb982fe7fef4c9154fd877c0db5dfbdda9b8307383a78cbed510a"
    end
  end

  def install
    bin.install "vivarium"
  end

  def caveats
    <<~EOS
      The native GUI is macOS-only: on macOS install the cask with 'brew install --cask vivarium'. Elsewhere use 'vivarium headless' for batch runs.
    EOS
  end

  test do
    # letsgo verifies before publishing that the binary reports this version,
    # so asserting it here catches a formula pointing at the wrong release
    # rather than merely proving the binary starts.
    assert_match "0.5.2-rc.1", shell_output("#{bin}/vivarium --version")
  end
end
